### ISSUE TITLE
Error in saving and reloading model

### ISSUE THREAD

**Issue by dikshitakambri** [dikshitakambri/Summarization-model#1]
I built and trained summarization model. For building and training we used old version of tensorflow.  But when I tried to save and reload the same model using pickle approach it showing error.
![image](https://user-images.githubusercontent.com/64687537/149615906-d8eddb03-aed8-44b6-bea1-2496afa10817.png)

Pickle approach reference: https://www.kaggle.com/prmohanty/python-how-to-save-and-load-ml-models

**Comment by harshagr18** [comment]
content/textummarization is not uploaded to the repository. Issue seems to be in the "pip install" command which needs to be explicitly specified to be command line code. Here it is trying to be executed as python code which throws the error.

Try adding an "!" to the start of it.

!pip install tensorflow==1.15.0 in the textsummarization.py file to fix.

**Comment by dikshitakambri** [comment]
@harshagr18 Initially I used "!", but it didn't worked so I removed that sign, still it is showing error.

**Comment by dikshitakambri** [comment]
Used **%tensorflow_version 1.x** instead of !pip install
And it worked
